FROM visiblevc/wordpress:0.26.0-php7.4

RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends lftp \
        libfreetype6-dev \
        libmcrypt-dev \
        libjpeg-dev \
        libpng-dev \
        ssh \
        jq
RUN sudo -E docker-php-ext-configure gd --with-freetype=/usr/freetype2 --with-jpeg=/usr
RUN sudo -E docker-php-ext-install pdo_mysql gd

SHELL ["/bin/sh", "-c"]

# Strict error/notice reporting
RUN sudo sh -c 'echo "error_reporting=E_ALL" >> /usr/local/etc/php/php.ini'

# Install xdebug for PHP live debugging in vscode
RUN yes | sudo pecl install xdebug \
    && sudo sh -c 'echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini' \
    && sudo sh -c 'echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini' \
    # xdebug.client_host is set during container creation
    && sudo sh -c 'echo "xdebug.client_port=9900" >> /usr/local/etc/php/conf.d/xdebug.ini' \
    && sudo sh -c 'echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini' \
    # consider setting up a cron job which periodically clears the log file so it doesn't get too big
    && sudo sh -c 'echo "xdebug.log_level=7" >> /usr/local/etc/php/conf.d/xdebug.ini' \
    && sudo sh -c 'echo "xdebug.log=/app/xdebug_log" >> /usr/local/etc/php/conf.d/xdebug.ini'

RUN touch /app/xdebug_log

CMD ["/run.sh"]
